# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a4df720726ab77a939bcdb347cb4ac28b554e82ea3ab6c627b0acfd561b9c676e95014060b011389b30ed3cfd06ee8a2562cd0438fbbfacc632f64ce0099be1b

test:
  secret_key_base: dba452d3a1e32dfde4bd05439c19d358c05cbcec712f03ab4d65c12c415ef87c582ed2f18174861310241aca281325e956da629fc99532988f96cb7441a65585

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
